const GET_COUNTRIES = 'GET_COUNTRIES'
const GET_DETAILS = 'GET_DETAILS'
const GET_ACTIVITIES = 'GET_ACTIVITIES'
const CREATE_ACTIVITY = 'CREATE_ACTIVITY'
const SORTING = 'SORTING'
const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT'
const FILTER_BY_ACTIVITY = 'FILTER_BY_ACTIVITY'


export {
    GET_COUNTRIES, CREATE_ACTIVITY, GET_DETAILS,
    SORTING, FILTER_BY_CONTINENT,
    FILTER_BY_ACTIVITY, GET_ACTIVITIES
}