const GET_COUNTRIES = 'GET_COUNTRIES'
const GET_DETAILS = 'GET_DETAILS'
const GET_ACTIVITIES = 'GET_ACTIVITIES'
const CREATE_ACTIVITY = 'CREATE_ACTIVITY'
const SORTING = 'SORTING'
const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT'
const FILTER_BY_ACTIVITY = 'FILTER_BY_ACTIVITY'
const RESET_ERROR = 'RESET_ERROR'
const FORM_ERROR = 'FORM_ERROR'
const COUNTRIES_ERROR = 'COUNTRIES_ERROR'
const ERROR = 'ERROR'

export {
    GET_COUNTRIES, CREATE_ACTIVITY, GET_DETAILS,
    SORTING, FILTER_BY_CONTINENT,
    FILTER_BY_ACTIVITY, GET_ACTIVITIES,
    FORM_ERROR, COUNTRIES_ERROR, RESET_ERROR,
    ERROR
}