const GET_COUNTRIES = 'GET_COUNTRIES'
const GET_DETAILS = 'GET_DETAILS'
const CREATE_ACTIVITY = 'CREATE_ACTIVITY'
const ORDER_AZ = 'ORDER_AZ'
const ORDER_ZA = 'ORDER_ZA'
const ORDER_MAX_TO_MIN = 'ORDER_MAX_TO_MIN'
const ORDER_MIN_TO_MAX = 'ORDER_MIN_TO_MAX'
const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT'
const FILTER_BY_ACTIVITY = 'FILTER_BY_ACTIVITY'

export {
    GET_COUNTRIES, CREATE_ACTIVITY, GET_DETAILS,
    ORDER_AZ, ORDER_ZA, ORDER_MAX_TO_MIN,
    ORDER_MIN_TO_MAX, FILTER_BY_CONTINENT,
    FILTER_BY_ACTIVITY
}